#pragma once
#include <algorithm>
#include <array>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <functional>
#include <future>
#include <iostream>
#include <mutex>
#include <queue>
#include <ranges>
#include <sstream>
#include <string>
#include <vector>
using std::operator""s;
using std::operator""sv;
